### PR TITLE
Execute only one instance.

### PR DESCRIPTION
**Pull request by ChangJoo-Park**
headset-electron execute multiple instances.
I think it should be execute only one instance.

https://electron.atom.io/docs/all/#appmakesingleinstancecallback

### CODE REVIEW

**Comment by danielravina** [comment]
Thanks for the PR! 
I wasn't able to reproduce the problem (on a mac). how did you identify multiple instances?

**Comment by ChangJoo-Park** [comment]
@danielravina  I using headset on Windows 10. Just run headset app two or more times.
image

image

**Comment by ChangJoo-Park** [comment]
It may be produce on Windows only. I don't have linux or macOS system 😢

**Comment by fcastilloec** [comment]
@ChangJoo-Park I can confirm that I can open multiple instances of Headset on various Linux distros

**Comment by ChangJoo-Park** [comment]
@fcastilloec Yes I saw scenarios you said on Windows 10.  
In my PR, headset runs only one instance. close well

**Comment by danielravina** [comment]
haha nice screenshot. thanks @fcastilloec for testing linux.
@ChangJoo-Park since it's not possible to run multiple instances (of any app) on a mac, can we revert the mac code?

**Comment by ChangJoo-Park** [comment]
I removed `makeSingleInstance` code from macOS

**Comment by danielravina** [comment]
oh sorry, one more thing! looks like the `yarn` change is not related (in general, lock file should always change when `package.json` changes) Can you revert that as well? 
As a sidenote - We removed `yarn` from the linux build and will do the same for windows and mac. 

Thank you! 🙏

**Comment by ChangJoo-Park** [comment]
@danielravina  Is it right?  :)

**Comment by fcastilloec** [comment]
I think what @danielravina was asking was to remove the yarn.lock file from the commit, so there's only 2 changed files (the linux and windows versions)

**Comment by ChangJoo-Park** [comment]
Close by #64  

I create new PR for remove useless commits 😞

**Pull request closed without merging**
