### PR TITLE
point darwin to new icon

### PR DESCRIPTION
**Pull request by danielravina**
Followup to #172

### CODE REVIEW

**Comment by Jackymancs4** [comment]
Hey @danielravina 

Thanks for merging #172 but I would like to suggest to not merge this PR 😅

**Comment by danielravina** [comment]
Why not?

**Comment by Jackymancs4** [comment]
Leaving a shallow reference (```tray = new Tray(path.join(__dirname, 'icons', 'Headset-16px.png'));``` allow the SO to automatically choose the icon with the best pixel density for the screen.

The ```name.png``` usually resolve to the best ```name@scale.png``` icon available.

On not-HD/Retina screens, forcing to use the @4 resolution (whith 38a3e3617d12d7fe41f03a296e4f25084cf684ac) will end in a software level rescaling that is usually not very pleasant, in my experience.

I suggest to leave the 16px icon as a fallback for <2013 macs.

**Comment by danielravina** [comment]
ok got it, thanks for the explanation! 

Do we need a `@2` as well?

**Comment by Jackymancs4** [comment]
> Do we need a @2 as well?

Not mandatory, but definetely appreciated since the ```@4x``` has a pretty hight pixel density. Definetely higher than actual Macbook screens.

**Comment by Jackymancs4** [comment]
For reference:

https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/image-size-and-resolution/
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

Not very useful on the pixel density stuff actually, but better than nothing.

**Comment by fcastilloec** [comment]
@danielravina I've tried testing this on my VM but because I don't have a high res display, I can't see any of the changes. Do you see the @4 icon instead of the new "headphones" icon? Later today, I'll try testing with a @2 icon and see if that shows up on my screen but I doubt it, given that it's a VM.

**Comment by danielravina** [comment]
@Jackymancs4 @fcastilloec 
added @2 icon, @1 icon and renamed the file.

**Comment by Jackymancs4** [comment]
Can confirm that my build on c3b9ab646e95ea26d02f7e997d7dcef7d25a41b6 looks awesome 👍

**Comment by fcastilloec** [comment]
@danielravina I think it's better to squash the commits this time so we don't get confused with the history where we're pointing at the wrong file.

**Comment by danielravina** [comment]
I was really frustrated with the way the icon looks and I didn't know how to make it better 😭 so I came up with this simple headphone icon. Thanks a bunch!

**Pull request merged**
