### PR TITLE
ci: remove publish to Homebrew

### PR DESCRIPTION
**Pull request by fcastilloec**

### CODE REVIEW

**Comment by waldyrious** [comment]
Out of curiosity, why was this removed? Do you prefer making the formula upgrades (semi-)manually, as in https://github.com/Homebrew/homebrew-cask/pull/100716?

**Comment by fcastilloec** [comment]
@waldyrious I rather keep the code but it was failing, I don't use macOS so I didn't have the time to double check what was happening and we needed to release again without it failing.
I know I should pass the environment variable with my token when running the main command, rather than what I was doing, but I'm not sure if it'll ask me for a username also, and I don't know what variable should store that.
I haven't found any documentation on how to properly do this

**Comment by waldyrious** [comment]
Thnks for the clarification. I haven't experimented with github actions yet, but I happen to use macOS, so if there's something like a sequence of commands I could run and relay the output of, or any similar way I could help, I'd be happy to assist.

**Comment by fcastilloec** [comment]
Thanks! The problem is that the only way to see what's happening is to actually run `bump-cask-pr` to update a package but without any new versions, we can't really do it. Running the same command with `--dry-run` will not give any errors either because it doesn't actually run the necessary git commands which are the ones that will produce the error seen in the CI run.

Have you manually run `bump-cask-pr` on a machine that doesn't have your git credentials store? If so, what command did you run? did you have any variables set (either in the command or on your .zshrc/bash config file)?

If you know of an app that needs updating, so I (or you) can test the command, that would be great. In the meantime, I think I'll re-add the code with some fixes, and hope that for the next release it'll work.

**Comment by waldyrious** [comment]
> Have you manually run `bump-cask-pr` on a machine that doesn't have your git credentials store? I

I have run the command before but not in a machine without the git credentials. I can certainly remove them temporarily and give it a try. Feel free to ping me when there's a new release of Headset (or you know of another program that could be updated in Homebrew) and I'll give it a shot.

**Pull request merged**
