### PR TITLE
Changes volume slider when updated from MPRIS

### PR DESCRIPTION
**Pull request by fcastilloec**
This will fix issue #78 
The fix will work with an updated version of Headset Core. If an older version is used (the current version), it doesn't cause any problems, so it's safe to be merged.

### CODE REVIEW

**Comment by fcastilloec** [comment]
This can be merged even if the core version hasn't been published yet. It will still work without problems

**Comment by danielravina** [comment]
core is published :)

**Comment by fcastilloec** [comment]
I guess just need to release a new version here :)

**Comment by danielravina** [comment]
Yes, I want to do it once https://github.com/headsetapp/headset-electron/tree/tiny-window is done (soon)

**Pull request merged**
